// The text this CLI generates: the version note pinned into every written SKILL.md, and
// the body of the marker block inserted into files we do not own.

import { readFileSync } from "node:fs";
import { join } from "node:path";

export const PIN_START = "<!-- surveyjs:pinned:start -->";
export const PIN_END = "<!-- surveyjs:pinned:end -->";

const PIN_PATTERN = /<!-- surveyjs:pinned:start -->[\s\S]*?<!-- surveyjs:pinned:end -->\n*/;
const FRONTMATTER = /^(---\r?\n[\s\S]*?\r?\n---\r?\n)/;

/** `` `survey-core@3.0.1` `` for a verified version, `` `survey-core@^3.0.1` `` for a range. */
export function describePackage(name, entry) {
  if (entry?.version) return `\`${name}@${entry.version}\``;
  if (entry?.range) return `\`${name}@${entry.range}\``;
  return `\`${name}\``;
}

function listPackages(packages, names) {
  return names.map((name) => describePackage(name, packages[name])).join(", ");
}

/**
 * Never states a version that was not verified. A caret range with no lockfile and no
 * node_modules is reported as the range it is, with the reason it could not be resolved.
 */
export function versionSentence({ packages, framework }) {
  const names = Object.keys(packages).sort();
  if (names.length === 0) {
    return (
      "No SurveyJS package was detected in this project, so the full skill set was installed. " +
      "These skills describe SurveyJS v3."
    );
  }

  const resolved = names.filter((name) => packages[name]?.version);
  const unresolved = names.filter((name) => !packages[name]?.version);
  const frameworkPart = framework ? ` UI framework: **${framework}**.` : "";
  const sentences = [];

  if (resolved.length > 0) sentences.push(`Installed in this project: ${listPackages(packages, resolved)}.`);
  if (unresolved.length > 0) {
    sentences.push(
      `${resolved.length > 0 ? "Also declared" : "Declared in this project"}: ` +
        `${listPackages(packages, unresolved)} — these are the ranges from \`package.json\`. No lockfile ` +
        "or `node_modules` was readable, so the exact installed version could not be verified; treat " +
        "the range as a lower bound and check the installed package if a documented API is missing."
    );
  }

  return `${sentences.join(" ")}${frameworkPart}`;
}

/** The note inserted directly after a written SKILL.md's frontmatter. */
export function pinnedNote(context) {
  const lines = [
    PIN_START,
    `> ${versionSentence(context)}`,
    ">",
    `> This copy was written by \`surveyjs-cli ${context.cliVersion}\` from ` +
      "[surveyjs/surveyjs-skills](https://github.com/surveyjs/surveyjs-skills) and describes those " +
      "versions. After upgrading SurveyJS, re-run `npx surveyjs-cli@latest init-agents`. If a documented " +
      "API is missing at runtime, check the typings inside the installed package before assuming the " +
      "skill is wrong.",
    PIN_END
  ];
  return lines.join("\n");
}

/**
 * Content for one file of a written skill. SKILL.md gets the pinned version note after its
 * frontmatter; reference files are copied byte-for-byte.
 */
export function renderSkillFile(skill, relativeFile, context) {
  const source = readFileSync(join(skill.dir, ...relativeFile.split("/")), "utf8");
  if (relativeFile !== "SKILL.md") return source;

  const stripped = source.replace(PIN_PATTERN, "");
  const note = `${pinnedNote(context)}\n\n`;
  const frontmatter = stripped.match(FRONTMATTER);
  if (!frontmatter) return `${note}${stripped}`;
  return `${frontmatter[1]}\n${note}${stripped.slice(frontmatter[1].length).replace(/^\r?\n+/, "")}`;
}

/**
 * Body of the marker block for a file we do not own.
 * @param {{ skills: Array, linkPrefix: string, skillsDirLabel: string, context: object }} options
 */
export function blockBody({ skills, linkPrefix, skillsDirLabel, context }) {
  const entries = skills.map((skill) => `- [\`${skill.name}\`](${linkPrefix}${skill.name}/SKILL.md) — ${skill.summary}`);

  return [
    "## SurveyJS",
    "",
    versionSentence(context),
    "",
    `The SurveyJS agent skills are installed in \`${skillsDirLabel}\`. Read the skill that matches the ` +
      "task before writing or changing SurveyJS code — they carry the current v3 API and the mistakes " +
      "to check generated code against:",
    "",
    ...entries,
    "",
    `Everything between the \`surveyjs:start\` and \`surveyjs:end\` markers is regenerated by ` +
      `\`surveyjs-cli ${context.cliVersion}\` (\`npx surveyjs-cli@latest init-agents\`). Put your own notes ` +
      "outside the markers."
  ].join("\n");
}
